codeforamerica/shiba

- src/main/resources/templates/uploadDocuments.html
IE11 didn't properly support arrow functions, `let`, or `const`.
This PR updates the uploadDocuments javascript to use old-school javascript (`var` and `function`) to make it more likely that our site will work on old browsers.
Note—I haven't actually tested the doc upload on any old browsers. We may be using other incompatible features that I don't know about
> Use old-school javascript for IE11 compatibility

- .github/workflows/deploy-to-staging.yml
- .github/workflows/run-tests-on-pr.yml
- build.gradle
Another attempt to speed up tests in CI.
- Also removes the postgres service from our test VMs since we are using H2 now
> Run db tests and unit test jobs in parallel; stop spinning up postgres for tests

- .github/workflows/deploy-to-staging.yml
- .github/workflows/run-tests-on-pr.yml
Just a small optimization that will save us a little bit of test time
> Cache gradle dependencies between test runs in CI

- src/main/java/org/codeforamerica/shiba/pages/emails/EmailContentCreator.java
- src/main/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClient.java
- src/main/resources/messages.properties
- src/test/java/org/codeforamerica/shiba/pages/emails/EmailContentCreatorTest.java
- src/test/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClientTest.java
[#177795275]
Modify emails coming from the demo environment to include messages notifying the recipient that they are receiving this email from demo
> Clarify in email confirmations from Demo that no real application was submitted

- build.gradle
We see these errors when we deploy to prod:
```
INFO -- : > Task :compileJava
INFO -- : warning: unknown enum constant When.MAYBE
INFO -- :   reason: class file for javax.annotation.meta.When not found
INFO -- : 
INFO -- : warning: unknown enum constant When.MAYBE
INFO -- : 
INFO -- :   reason: class file for javax.annotation.meta.When not found
INFO -- : 
INFO -- : warning: unknown enum constant When.MAYBE
INFO -- : 
INFO -- :   reason: class file for javax.annotation.meta.When not found
INFO -- : 
INFO -- : warning: unknown enum constant When.MAYBE
INFO -- : 
INFO -- :   reason: class file for javax.annotation.meta.When not found
INFO -- : 
```
This fixes that apparently https://stackoverflow.com/questions/53326271/spring-nullable-annotation-generates-unknown-enum-constant-warning
> add findbugs to provide missing annotation

- src/test/java/org/codeforamerica/shiba/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/newjourneys/LaterDocsJourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/journeys/UserJourneyPageTest.java
- Combine all of the later docs E2E tests into a single journey test
- Put the new test in a distinct package called "newjourneys". (Totally open to suggestions about better names!) This is to draw a line between our suite of new, happy path journey tests and our old E2E tests that we will ultimately be converting to mockmvc or unit tests. 
- Just combining these tests seems to have shaved ~7s off of the total test time, which is a good sign that this approach of making a small number of looong Journey tests will pay off.
[#178367703]
> Create a new journey test for the later docs flow

- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParserV2.java
- src/main/java/org/codeforamerica/shiba/application/parsers/GrossMonthlyIncomeParser.java
- src/main/java/org/codeforamerica/shiba/application/parsers/SnapExpeditedEligibilityParser.java
- src/main/java/org/codeforamerica/shiba/application/parsers/TotalIncomeParser.java
- src/main/java/org/codeforamerica/shiba/output/caf/GrossMonthlyIncomeMapper.java
- src/test/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParser2Test.java
- src/test/java/org/codeforamerica/shiba/application/parsers/GrossMonthlyIncomeParserTest.java
- src/test/java/org/codeforamerica/shiba/pages/data/TestApplicationDataBuilder.java
Refactor GrossMonthlyIncomeParser to not use the parsing configuration and instead use a new ApplicationDataParserV2 (which would hypothetically replace ApplicationDataParser).
ApplicationDataParserV2 has a `Field` enum which would correspond to the parsing-coordinates in the parsing-config
Pros:
- ApplicationDataParserV2 is static so it does not need to be initialized or passed in constructors.
Cons:
- All the tests would need to be updated to setup application data with the expected values or the static methods would need to be mocked, which is tedious but not necessarily bad
- Probably less readable than putting into a config file
[#178403952]
> Refactor GrossMonthlyIncomeParser without config

- src/main/java/org/codeforamerica/shiba/pages/DocRecommendationMessageService.java
- src/test/java/org/codeforamerica/shiba/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/newjourneys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/DocRecommendationMessageServiceTest.java
- src/test/java/org/codeforamerica/shiba/pages/journeys/AccessibilityJourneyPageTest.java
- src/test/java/org/codeforamerica/shiba/pages/journeys/DocumentUploadJourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/journeys/DocumentsTest.java
- src/test/java/org/codeforamerica/shiba/pages/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/journeys/UserJourneyMockMvcTest.java
This does not completely remove the E2E tests for document uploads, but it combines most of them and converts most of the others to MockMvc. 
For me this reduces the execution time of DocumentsTest from 2m 35s to 27s, which is a pretty good gain!
We were not using a real documentRepositoryService in our JourneyTests, which is a problem because we want to be sure that functionality continues working. This makes it so we are once again using an actual documentRepositoryService.
Unfortunately, using an actual document repository service causes the accessibility tests to fail. That is something we need to fix, but is out of scope for this PR. [Here's a chore for addressing that](https://www.pivotaltracker.com/n/projects/2441723)
> Reduce the number of end to end tests for uploading documents; actually upload documents to Azure in tests

- .github/workflows/run-percy.yml
- src/test/java/org/codeforamerica/shiba/journeys/AccessibilityJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/DocumentUploadJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/LaterDocsJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/MinimumSnapFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/UserJourneyMockMvcTest.java
We have converted all of the old tests that extended `JourneyTest` so we can now consolidate the journey tests into one package
> Move all journey tests to `journeys` package; remove `newJourneys`

- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/MinimumSnapFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/LocalePreferenceSelectionTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/SeleniumFactory.java
- src/test/java/org/codeforamerica/shiba/testutilities/WebDriverConfiguration.java
Instead of booting up chrome for each individual test. The hope is that this will reduce the test time for our Minnesota engineer friends.
> Reuse the same chrome session between webdriver tests

- build.gradle
- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/ShibaApplication.java
- src/main/java/org/codeforamerica/shiba/configurations/ShedLockConfig.java
- src/main/resources/db/migration/V29__add-shedlock-table.sql
Create shedlock table to run only one instance of the ResubmissionService regardless of number of containers
[#179048278]
> Shedlock Configuration for SchedulerLock

- build.gradle
- "com.sun.xml.bind:jaxb-xjc:2.3.4" is described as the "old JAXB runtime". Source: https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl/2.2.11
- This stackoverflow post explains what artifacts should be used now. The answer is glassfish jaxb https://stackoverflow.com/questions/26413431/which-artifacts-should-i-use-for-jaxb-ri-in-my-maven-project
- We can get glassfish versions from the spring-boot-bom, meaning we will no longer get jaxb update PRs!
- Updating this will make https://github.com/codeforamerica/shiba/pull/340 irrelevant
[#179330988]
> Use glassfish for JAXB instead of com.sun.xml.bind:jaxb-xjc.

- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
- I'm sick of seeing these errors in sentry
- Now if a user requests a nonexistant page, they will just be redirected to the error page.
- There should be no functional change here from a user standpoint
[#179092595]
> Avoid NullPointerException if client tries to go to a nonexistant page

- src/main/resources/db/migration/V33__create-application-status-table.sql
- Not adding fk reference to application_id for now to avoid complications with that constraint. We can add it later if needed
- Setting `WITHOUT TIME ZONE` for timestamps to match completed_at in applications table
- Not including any tests with this change since it's just adding an unused table. Tests can be added with the read/write changes
- Reusing TRIGGER from previous migration for updating `updated_at` column
- Dropping deprecated research table
[#180018044]
> Adding new status table migration

- src/main/java/db/migration/V34__BackfillApplicationStatus.java
- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/Application.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationStatus.java
- src/main/java/org/codeforamerica/shiba/mnit/AlfrescoWebServiceClient.java
- src/main/java/org/codeforamerica/shiba/mnit/FilenetWebServiceClient.java
- src/main/java/org/codeforamerica/shiba/output/MnitDocumentConsumer.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/RoutingDecisionService.java
- src/main/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClient.java
- src/test/java/org/codeforamerica/shiba/ResubmissionServiceTest.java
- src/test/java/org/codeforamerica/shiba/application/ApplicationRepositoryTest.java
- src/test/java/org/codeforamerica/shiba/mnit/AlfrescoWebServiceClientTest.java
- src/test/java/org/codeforamerica/shiba/mnit/FilenetWebServiceClientTest.java
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
- src/test/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClientTest.java
- src/test/resources/test-schema-init.sql
- Doesn't remove "in_progress" entries if applicant changes program selection
- Starts saving statuses when both document type and routing destination are present (after choosePrograms page)
> Write to application status table

- src/main/java/org/codeforamerica/shiba/configurations/RestTemplateConfiguration.java
- src/main/java/org/codeforamerica/shiba/mnit/FilenetWebServiceClient.java
Extract bean definition to avoid a circular reference
The error this fixes looks like this:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
The dependencies of some of the beans in the application context form a cycle:
┌──->──┐
|  filenetWebServiceClient (field private org.springframework.web.client.RestTemplate org.codeforamerica.shiba.mnit.FilenetWebServiceClient.restTemplate)
└──<-──┘
Action:
Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
```
> fix bug where app won't start due to circular reference

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/output/DocumentUploadEmailService.java
- src/main/resources/application.yaml
- src/test/resources/application-test.yaml
This makes two changes:
1. ResubmissionService should not run in the background during our tests
- Add configurable initialDelayString (that defaults to 0). 
- This maintains the existing behavior for the regular app, but allows us to add an arbitrarily long wait time before the first run of the ResubmissionService in our tests, effectively disabling it for tests.
2. Disable DocumentUploadEmailService in tests
- make cron expression configurable.
- Keep current configuration for the actual app
- use the special character `-` to disable the scheduled process in tests
This shouldn't change anything for the actual app and should only affect tests.
> Fix flaky tests resulting from @Scheduled processes

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/output/DocumentUploadEmailService.java
- src/main/resources/application.yaml
- src/test/java/org/codeforamerica/shiba/AppsStuckInProgressResubmissionTest.java
- src/test/resources/application-test.yaml
- Resubmission over now only occurs on apps completed half an hour after the last retry: 8 hours after submission.
- Lock esbResubmissionTask to run once per node every hour on no more than 50 applications
[#181451258]
> Run ESB resubmissions once per node

- src/main/java/org/codeforamerica/shiba/configurations/SpringAsyncConfiguration.java
- src/main/resources/application.yaml
- src/test/resources/application-test.yaml
- start with 10 threads for ESB submissions (default is 1)
- lower queue capacity so that more threads will spin up to complete tasks (default queue capacity is integer.max)
By default we have 1 thread and a large queue for submitting applications via ESB. This is usually fine unless we're experiencing failures/retries on submission in which case, applications could be piling up in the queue waiting (up to 3 hours) for each submission to go through or fail. If we restart the application during this time, we'll lose all the queued events. 
By lowering the queue capacity, we can force more threads to spin up to send the applications.
> Overwriting default configurations for ThreadExecutor

- src/main/java/org/codeforamerica/shiba/application/Application.java
- src/main/java/org/codeforamerica/shiba/output/MnitDocumentConsumer.java
- src/main/java/org/codeforamerica/shiba/output/caf/FilenameGenerator.java
- src/main/java/org/codeforamerica/shiba/output/pdf/PdfGenerator.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/resources/messages.properties
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
- Add client-side check for empty files. Empty files are skipped from submission anyways - this will make it more clear to the client as well 
- Update for resubmission. If all docs cant be sent (are skipped) for some reason, UPLOADED_DOC status will be set to "undeliverable"
- Update for generating filenames for uploaded_docs. Skipped documents are not included in total doc count
- Renamed thumbnail files to include "thumbnail" in the filename
> Adding check for docs that cant be sent

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/application/DocumentStatusRepository.java
- src/main/java/org/codeforamerica/shiba/application/Status.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/config/LandmarkPagesConfiguration.java
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/AppsStuckSendingResubmissionTest.java
- src/test/java/org/codeforamerica/shiba/AppsWithBlankStatusResubmissionTest.java
- src/test/java/org/codeforamerica/shiba/application/DocumentStatusRepositoryTest.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
- src/test/resources/pages-config/test-pages-controller.yaml
Deprecating IN_PROGRESS status. This is no longer needed. 
- We now expect only to see applications stuck in "sending" status if events are dropped/interrupted.
- Leaving in resubmission logic to find blank statuses for now, we dont expect to see these anymore
- Fixes issue with applications that only need to be sent to tribal nations getting sent twice because of unintentional in_progress status for county triggering resubmission
> Deprecated in progress

- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
[#182280319]
Chibuisi Enyia <cenyia@codeforamerica.org>
> Updated medical expenses helptext
