- src/main/java/org/codeforamerica/shiba/pages/config/ApplicationConfiguration.java
- src/main/java/org/codeforamerica/shiba/pages/config/PageConfiguration.java
- src/main/resources/dev-pages-config.yaml
> Refactor - Extracted conditions into reusable anchors

- src/main/java/org/codeforamerica/shiba/pages/config/Validation.java
- src/test/java/org/codeforamerica/shiba/pages/ValidationPageTest.java
> Updated email validation to trim whitespaces for validation.

- src/main/java/org/codeforamerica/shiba/output/pdf/PDFBoxFieldFiller.java
- src/main/resources/templates/uploadDocuments.html
- src/test/java/org/codeforamerica/shiba/output/pdf/PDFBoxFieldFillerTest.java
> Strip out unsupported unicode 

- build.gradle
- src/main/java/org/codeforamerica/shiba/MonitoringService.java
- src/main/java/org/codeforamerica/shiba/SentryClient.java
- src/main/java/org/codeforamerica/shiba/configurations/RetryConfiguration.java
- src/main/java/org/codeforamerica/shiba/mnit/MnitEsbWebServiceClient.java
- src/main/resources/application.yaml
- src/test/java/org/codeforamerica/shiba/mnit/MnitEsbWebServiceClientTest.java
- src/test/resources/application-test.yaml
[Tracker story](https://www.pivotaltracker.com/story/show/176619094)
> Implement ESB submission retry logic

- .gitignore
- build.gradle
- src/main/java/org/codeforamerica/shiba/SessionLogFilter.java
- src/main/java/org/codeforamerica/shiba/configurations/FilterConfig.java
- src/main/resources/logback-spring.xml
[#175810484]
SHIBA is migrating from Kibana logs to Datadog for logging
> Setting up Datadog Logs for Staging

- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/pages/UserJourneyPageTest.java
[#176042793]
Co-authored-by: Andrew Edstrom <aedstrom@codeforamerica.org>
> Remove GRH Program Selection for Household Member

- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/pages/features/CCAPTest.java
- src/test/java/org/codeforamerica/shiba/pages/features/DocumentsTest.java
- src/test/java/org/codeforamerica/shiba/pages/features/LivingSituationTest.java
- src/test/java/org/codeforamerica/shiba/pages/features/MillionDollarQuestionTest.java
- Moved livingSituation screen to after the household flow (or household ask if live alone)
[#177212415]
> Moved LivingSituation and modified associated tests

- src/test/java/org/codeforamerica/shiba/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/metrics/ApplicationRepositoryTest.java
> Make tests pass on Windows

- src/main/java/org/codeforamerica/shiba/output/caf/CcapExpeditedEligibilityDecider.java
- src/test/java/org/codeforamerica/shiba/output/caf/CcapExpeditedEligibilityDeciderTest.java
> Update expedited CCAP logic

- derived-values-config-schema.json
- src/main/resources/derived-value-config.yaml
- Remove logical operator for single conditions
- Extracted common config for conditions
[#177895436]
> Cleanup derived-values config

- src/main/java/org/codeforamerica/shiba/pages/events/ApplicationEvent.java
- src/main/java/org/codeforamerica/shiba/pages/events/ApplicationEventListener.java
- src/main/java/org/codeforamerica/shiba/pages/events/ApplicationSubmittedEvent.java
- src/main/java/org/codeforamerica/shiba/pages/events/ApplicationSubmittedListener.java
- src/main/java/org/codeforamerica/shiba/pages/events/UploadedDocumentsSubmittedEvent.java
- src/main/java/org/codeforamerica/shiba/pages/events/UploadedDocumentsSubmittedListener.java
> Record all ApplicationEvent properties to logger

- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/resources/templates/fragments/footer.html
> Add zip code and additional information to Intercom

- src/main/java/org/codeforamerica/shiba/application/Application.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/test/java/org/codeforamerica/shiba/application/ApplicationTest.java
> Save applicationData without thumbnail dataURLs

- src/main/resources/templates/uploadDocuments.html
- src/test/java/org/codeforamerica/shiba/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/TestUtils.java
- src/test/java/org/codeforamerica/shiba/pages/journeys/DocumentsTest.java
- Chronological ordering
[#177271688]
> Update Doc upload ordering

- src/main/java/org/codeforamerica/shiba/application/parsers/CcapExpeditedEligibilityParser.java
- src/main/java/org/codeforamerica/shiba/application/parsers/SnapExpeditedEligibilityParser.java
- src/main/java/org/codeforamerica/shiba/output/caf/CcapExpeditedEligibilityDecider.java
- src/test/java/org/codeforamerica/shiba/application/parsers/CcapExpeditedEligibilityParserTest.java
- src/test/java/org/codeforamerica/shiba/application/parsers/GrossMonthlyIncomeParserTest.java
- src/test/java/org/codeforamerica/shiba/application/parsers/SnapExpeditedEligibilityParserTest.java
- src/test/java/org/codeforamerica/shiba/output/caf/CcapExpeditedEligibilityDeciderTest.java
- src/test/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClientTest.java
- src/test/java/org/codeforamerica/shiba/pages/enrichment/smartstreets/SmartyStreetClientTest.java
This shaves about 50s off of the unit tests in CI!
> Remove @SpringBootTest from tests that didn't use a real web environment

- src/main/java/org/codeforamerica/shiba/application/ApplicationDataEncryptor.java
- src/main/java/org/codeforamerica/shiba/pages/data/Subworkflow.java
- src/test/java/org/codeforamerica/shiba/application/ApplicationDataEncryptorTest.java
> Leave empty SSN blank rather than encrypting it

- src/main/java/org/codeforamerica/shiba/Utils.java
- src/main/java/org/codeforamerica/shiba/internationalization/InternationalizationUtils.java
- src/main/java/org/codeforamerica/shiba/internationalization/LocaleSpecificMessageSource.java
- src/main/java/org/codeforamerica/shiba/pages/PageUtils.java
- src/main/java/org/codeforamerica/shiba/pages/SuccessMessageService.java
- src/main/resources/messages.properties
- src/test/java/org/codeforamerica/shiba/pages/SuccessMessageServiceTest.java
https://www.pivotaltracker.com/story/show/178115548
> Comma separated list for programs on success screen

- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/pages/journeys/DocumentsTest.java
applicant or household member chooses the SNAP program.
[#178077761]
> Applicants can now get to the preparingMealsTogether page if either the

- src/main/java/org/codeforamerica/shiba/Money.java
- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParser.java
- src/main/java/org/codeforamerica/shiba/application/parsers/SnapExpeditedEligibilityParser.java
- src/main/java/org/codeforamerica/shiba/application/parsers/TotalIncomeParser.java
- src/main/java/org/codeforamerica/shiba/output/caf/HourlyJobIncomeInformation.java
- src/main/java/org/codeforamerica/shiba/output/caf/JobIncomeInformation.java
- src/main/java/org/codeforamerica/shiba/output/caf/LastThirtyDaysJobIncomeInformation.java
- src/main/java/org/codeforamerica/shiba/output/caf/NonHourlyJobIncomeInformation.java
- src/main/java/org/codeforamerica/shiba/output/caf/SnapExpeditedEligibilityDecider.java
- src/main/java/org/codeforamerica/shiba/output/caf/SnapExpeditedEligibilityParameters.java
- src/main/java/org/codeforamerica/shiba/output/caf/TotalIncome.java
- src/main/java/org/codeforamerica/shiba/output/caf/TotalIncomeCalculator.java
- src/main/java/org/codeforamerica/shiba/output/caf/UtilityDeductionCalculator.java
- src/test/java/org/codeforamerica/shiba/application/parsers/SnapExpeditedEligibilityParserTest.java
- src/test/java/org/codeforamerica/shiba/output/TotalIncomeCalculatorTest.java
- src/test/java/org/codeforamerica/shiba/output/TotalIncomeParserTest.java
- src/test/java/org/codeforamerica/shiba/output/caf/GrossMonthlyIncomeMapperTest.java
- src/test/java/org/codeforamerica/shiba/output/caf/HourlyJobIncomeInformationTest.java
- src/test/java/org/codeforamerica/shiba/output/caf/NonHourlyJobIncomeInformationTest.java
- src/test/java/org/codeforamerica/shiba/output/caf/SnapExpeditedEligibilityDeciderTest.java
- src/test/java/org/codeforamerica/shiba/output/caf/ThirtyDayIncomeMapperTest.java
- src/test/java/org/codeforamerica/shiba/output/caf/UtilityDeductionCalculatorTest.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfIntegrationTest.java
- Coerces into whole numbers
- Creating big BigDecimals greater with greater that 14 digits from doubles can have issues with precision but doesn't feel too likely
[#177988195]
> Refactor Doubles into Money

- src/main/java/org/codeforamerica/shiba/pages/config/Validation.java
- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/pages/ValidationPageTest.java
- src/test/resources/pages-config/test-validation.yaml
> Adding back-end validation for hours-per-week on job page.

- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/test/java/org/codeforamerica/shiba/pages/HouseholdTest.java
[#178273995]
Co-authored-by: Andrew E<aedstrom@codeforamerica.org>
> Bug fix for deleting iteration that doesnt exist

- build.gradle
- src/main/java/org/codeforamerica/shiba/application/parsers/EmailParser.java
- src/main/java/org/codeforamerica/shiba/pages/events/ApplicationSubmittedListener.java
- src/main/java/org/codeforamerica/shiba/pages/events/UploadedDocumentsSubmittedListener.java
- src/test/java/org/codeforamerica/shiba/application/parsers/EmailParserTest.java
- src/test/java/org/codeforamerica/shiba/pages/events/ApplicationSubmittedListenerTest.java
- src/test/java/org/codeforamerica/shiba/pages/events/UploadedDocumentsSubmittedListenerTest.java
- src/test/resources/test-parsing-config.yaml
> Refactor EmailParser

- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/pages/journeys/UserJourneyPageTest.java
[#176686128]
Co-authored-by: John Bisek <john.bisek@state.mn.us>
> Added "additional info" page to min flow

- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
> Update completed_at and time_to_complete in the later docs flow

- src/test/java/org/codeforamerica/shiba/application/parsers/SnapExpeditedEligibilityParserTest.java
Refactor - extracting duplicate code and using TestApplicationDataBuilder
No functional changes to the parser itself
> Refactor SnapExpeditedEligibilityParserTest

- src/main/java/org/codeforamerica/shiba/application/ApplicationFactory.java
- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParserV2.java
- src/main/java/org/codeforamerica/shiba/application/parsers/CountyParser.java
- src/main/resources/parsing-config.yaml
- src/test/java/org/codeforamerica/shiba/application/ApplicationFactoryTest.java
- src/test/java/org/codeforamerica/shiba/application/parsers/CountyParserTest.java
- src/test/java/org/codeforamerica/shiba/pages/data/TestApplicationDataBuilder.java
- src/test/resources/test-parsing-config.yaml
This parser still needs to be a component since it uses the feature flag config as well
[#178473427]
> Refactor county parser to not use config

- src/main/java/org/codeforamerica/shiba/Money.java
- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParserV2.java
- src/main/java/org/codeforamerica/shiba/application/parsers/SnapExpeditedEligibilityParser.java
- src/main/java/org/codeforamerica/shiba/application/parsers/TotalIncomeParser.java
- src/test/java/org/codeforamerica/shiba/application/parsers/SnapExpeditedEligibilityParserTest.java
- src/test/java/org/codeforamerica/shiba/output/TotalIncomeParserTest.java
- src/test/java/org/codeforamerica/shiba/pages/data/TestApplicationDataBuilder.java
- Moved "defaultValue" to Field
[#178473408]
> Refactoring  SnapExpeditedEligibilityParser, TotalIncomeParser to not use parsing configuration

- src/test/java/org/codeforamerica/shiba/newjourneys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/newjourneys/LaterDocsJourneyTest.java
- src/test/java/org/codeforamerica/shiba/newjourneys/MinimumSnapFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfIntegrationTest.java
- src/test/java/org/codeforamerica/shiba/pages/journeys/DocumentsTest.java
- src/test/java/org/codeforamerica/shiba/pages/journeys/JourneyTest.java
> Add Full Flow Journey Test

- src/main/resources/messages.properties
- src/test/java/org/codeforamerica/shiba/pages/emails/EmailContentCreatorTest.java
> Update client confirmation email copy

- src/main/java/org/codeforamerica/shiba/pages/DocRecommendationMessageService.java
- src/test/java/org/codeforamerica/shiba/pages/DocRecommendationMessageServiceTest.java
> Proof of housing will not show up in the document recommendations during

- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/newjourneys/MinimumSnapFlowJourneyTest.java
> Implement: City and zip

- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParser.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/config/Validation.java
- src/main/java/org/codeforamerica/shiba/pages/enrichment/AddressEnrichment.java
- src/main/java/org/codeforamerica/shiba/pages/enrichment/DateOfBirthEnrichment.java
- src/main/java/org/codeforamerica/shiba/pages/enrichment/Enrichment.java
- src/main/java/org/codeforamerica/shiba/pages/enrichment/HomeAddressEnrichment.java
- src/main/java/org/codeforamerica/shiba/pages/enrichment/HouseholdMemberDateOfBirthEnrichment.java
- src/main/java/org/codeforamerica/shiba/pages/enrichment/MailingAddressEnrichment.java
- src/main/java/org/codeforamerica/shiba/pages/enrichment/MatchInfoDateOfBirthEnrichment.java
- src/main/java/org/codeforamerica/shiba/pages/enrichment/PersonalInfoDateOfBirthEnrichment.java
- src/main/java/org/codeforamerica/shiba/pages/enrichment/ZipcodeToCountyEnrichment.java
- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/pages/EnrichmentPageTest.java
- src/test/java/org/codeforamerica/shiba/pages/ValidationPageTest.java
- src/test/java/org/codeforamerica/shiba/pages/data/TestApplicationDataBuilder.java
- src/test/java/org/codeforamerica/shiba/pages/enrichment/AddressEnrichmentTest.java
- src/test/java/org/codeforamerica/shiba/pages/enrichment/DateOfBirthEnrichmentTest.java
- src/test/java/org/codeforamerica/shiba/pages/enrichment/ZipcodeToCountyEnrichmentTest.java
- src/test/resources/pages-config/test-validation.yaml
> DOB is validated to > 1/1/1900 and < current date and saved as

- src/main/resources/pages-config.yaml
[#178504736]
Co-authored-by: John Bisek <john.bisek@state.mn.us>
> Simplify complex conditions

- src/test/java/org/codeforamerica/shiba/AbstractShibaMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/pages/ValidationPageTest.java
- src/test/java/org/codeforamerica/shiba/pages/ValidationTest.java
> Convert some of ValidationPageTest to use MockMvc

- src/main/java/org/codeforamerica/shiba/configurations/SecurityConfiguration.java
- src/main/java/org/codeforamerica/shiba/output/ResendFailedEmailController.java
- src/test/java/org/codeforamerica/shiba/output/ResendFailedEmailControllerTest.java
[#178805759]
Co-authored-by: Andrew Edstrom <aedstrom@codeforamerica.org>
> Implement ResendFailedEmailController

- src/main/java/org/codeforamerica/shiba/inputconditions/Condition.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/data/ApplicationData.java
- src/main/java/org/codeforamerica/shiba/pages/data/DatasourcePages.java
- src/main/java/org/codeforamerica/shiba/pages/data/PagesData.java
- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/main/resources/static/shiba.js
- src/main/resources/templates/fragments/chooseProgramsAlertBox.html
- src/main/resources/templates/fragments/chooseProgramsCheckboxes.html
- src/main/resources/templates/fragments/icons/icon-people.html
- src/main/resources/templates/jobBuilder.html
- src/test/java/org/codeforamerica/shiba/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/AbstractShibaMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/CCAPMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/framework/FormPage.java
- src/test/resources/pages-config/test-conditional-rendering.yaml
- src/test/resources/pages-config/test-feature-flag.yaml
- src/test/resources/pages-config/test-user-decision-navigation.yaml
> 'None' in Program Selection for Applicant

- src/main/java/org/codeforamerica/shiba/inputconditions/ValueMatcher.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/main/resources/templates/fragments/mailContextFragment.html
- src/main/resources/templates/fragments/noProgramsContextFragment.html
- src/main/resources/templates/noProgramsSelected.html
- src/test/java/org/codeforamerica/shiba/AbstractShibaMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/NoProgramSelectionsMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/framework/ValidationTest.java
- src/test/resources/pages-config/test-validation.yaml
> Implement apply for no programs error page

- src/test/java/org/codeforamerica/shiba/NoProgramSelectionsMockMvcTest.java
Co-authored-by: John Bisek <john.bisek@state.mn.us.>
> Test resolving merging conflicts

- src/main/java/org/codeforamerica/shiba/output/caf/FileNameGenerator.java
- src/test/java/org/codeforamerica/shiba/output/applicationinputsmappers/FileNameGeneratorTest.java
[#178748430]
Co-authored-by: John Bisek <john.bisek@state.mn.us.>
> Update uploaded document filenames for Hennepin

- src/main/resources/static/shiba.js
- src/test/java/org/codeforamerica/shiba/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/newjourneys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/Page.java
> Fix bug where no programs follow up would show after selecting none

- src/main/java/org/codeforamerica/shiba/configurations/CityInfoConfiguration.java
- src/main/java/org/codeforamerica/shiba/configurations/CityInfoConfigurationFactory.java
- src/main/java/org/codeforamerica/shiba/configurations/CityInfoConfigurationFactoryAppConfig.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/config/Validation.java
- src/main/resources/city-to-zipcode-and-county-mapping.yaml
- src/main/resources/messages.properties
- src/main/resources/messages_es.properties
- src/main/resources/pages-config.yaml
- src/main/resources/templates/fragments/selectCityCustomInput.html
- src/test/java/org/codeforamerica/shiba/newjourneys/MinimumSnapFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/AbstractPageControllerTest.java
- src/test/java/org/codeforamerica/shiba/pages/Page.java
Outstanding question on what to do for "Other"
> Add "select city" drop-down for General Delivery

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/ShibaApplication.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/application/Status.java
- src/main/java/org/codeforamerica/shiba/output/MnitDocumentConsumer.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/emails/EmailClient.java
- src/main/java/org/codeforamerica/shiba/pages/emails/EmailContentCreator.java
- src/main/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClient.java
- src/main/java/org/codeforamerica/shiba/pages/events/UploadedDocumentsSubmittedListener.java
- src/main/resources/application.yaml
- src/main/resources/messages.properties
- src/test/java/org/codeforamerica/shiba/ResubmissionServiceTest.java
- src/test/java/org/codeforamerica/shiba/application/ApplicationRepositoryTest.java
- src/test/java/org/codeforamerica/shiba/pages/emails/EmailContentCreatorTest.java
- src/test/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClientTest.java
- src/test/java/org/codeforamerica/shiba/pages/events/UploadedDocumentsSubmittedListenerTest.java
Auto re-submit apps/docs with a `delivery_failed` status on a 12 hour cadence.
[#178700133]
Co-authored-by: Sree P <sprasad@codeforamerica.org>
Co-authored-by: Andrew E <aedstrom@codeforamerica.org>
Co-authored-by: Britney E <bepps@codeforamerica.org>
> Resubmit via email

- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParser.java
- src/main/java/org/codeforamerica/shiba/inputconditions/Condition.java
- src/main/java/org/codeforamerica/shiba/output/caf/HomeAddressStreetMapper.java
- src/main/java/org/codeforamerica/shiba/output/caf/MailingAddressStreetMapper.java
- src/main/java/org/codeforamerica/shiba/pages/data/DatasourcePages.java
- src/main/resources/derived-value-config.yaml
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/journeys/MinimumSnapFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/applicationinputsmappers/HomeAddressStreetMapperTest.java
- src/test/java/org/codeforamerica/shiba/output/applicationinputsmappers/MailingAddressStreetMapperTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/TestApplicationDataBuilder.java
adding missing input
Building datasourcepages for derived values to be able to use conditions with subworkflows
> Write no-address to PDF

- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParser.java
- src/main/java/org/codeforamerica/shiba/application/parsers/CountyParser.java
- src/test/java/org/codeforamerica/shiba/testutilities/TestApplicationDataBuilder.java
> homeAddress2 is the key name but not the page name.

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/Application.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/application/Status.java
- src/test/java/org/codeforamerica/shiba/application/ApplicationRepositoryTest.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
[#177798225]
Co-authored-by: Britney E <bepps@codeforamerica.org>
> Resubmit applications that have been in_progress longer than a day

- src/main/resources/application-demo.yaml
- src/main/resources/application-production.yaml
- src/test/java/org/codeforamerica/shiba/CCAPMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/NoProgramSelectionsMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/journeys/AccessibilityJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/MinimumSnapFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/pages/LivingSituationTest.java
- src/test/java/org/codeforamerica/shiba/pages/MetricsTest.java
- src/test/java/org/codeforamerica/shiba/pages/UserJourneyMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
- src/test/resources/application-test.yaml
- Set flags to on
- Updated tests to default for flag on
> Update release flags to "ON" for applying without an address

- src/main/resources/static/shiba.js
- src/main/resources/templates/fragments/addressValidationInput.html
- src/main/resources/templates/fragments/pageTemplateFragment.html
- src/main/resources/templates/householdDeleteWarningPage.html
- src/main/resources/templates/jobDeleteWarningPage.html
- src/main/resources/templates/jobRedirectPage.html
- src/main/resources/templates/success.html
- src/main/resources/templates/uploadDocumentsDeleteWarningPage.html
- src/main/resources/templates/warningPage.html
- src/test/java/org/codeforamerica/shiba/framework/GoBackButtonE2ETest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/Page.java
https://www.pivotaltracker.com/story/show/178872928
> Disable submit button after it is clicked

- src/main/resources/static/shiba.css
[#177365396]
Co-authored-by: John Bisek <john.bisek@state.mn.us.>
> Update Hoverstate/Inactive state for Doc upload

- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/Page.java
[#178979528]
Co-authored-by: John Bisek <john.bisek@state.mn.us.>
> Update expedited calculation to include cost of room & board

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/test/java/org/codeforamerica/shiba/application/ApplicationRepositoryTest.java
> Fix the resubmission issue and turn the resubmission logic back on

- src/main/java/org/codeforamerica/shiba/pages/emails/EmailContentCreator.java
- src/main/resources/messages.properties
- src/test/java/org/codeforamerica/shiba/pages/emails/EmailContentCreatorTest.java
[#179057698]
Co-authored-by: Andrew Edstrom <aedstrom@codeforamerica.org>
> Update resubmission email copy

- src/main/resources/static/shiba.css
- src/main/resources/templates/uploadDocuments.html
> Fix plus icon loading issue (and error box rendering issue)

- src/main/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClient.java
- src/main/resources/messages.properties
- src/test/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClientTest.java
> Localize the subject line provided in client email.

- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/main/resources/templates/documentSubmitConfirmation.html
- src/main/resources/templates/fragments/documentsSuccessContextFragment.html
- src/main/resources/templates/uploadDocuments.html
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/LaterDocsJourneyTest.java
[#179011675]
Co-authored-by: Eric J <eric.m.johnson@state.mn.us>
> Adding document upload confirmation screen

- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParser.java
- src/main/java/org/codeforamerica/shiba/output/ApplicationInput.java
- src/main/java/org/codeforamerica/shiba/output/caf/CoverPageInputsMapper.java
- src/test/java/org/codeforamerica/shiba/output/applicationinputsmappers/CoverPageInputsMapperTest.java
https://www.pivotaltracker.com/story/show/179033523
> Refactor coverpageinputsmapper and fix bug

- src/main/resources/static/shiba.css
- src/main/resources/templates/fragments/date-input.html
- src/main/resources/templates/fragments/form-question-prompt.html
- src/main/resources/templates/fragments/people-checkbox-input.html
- src/test/java/org/codeforamerica/shiba/framework/InputsPageMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/framework/ValidationTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/FormPage.java
- src/test/resources/pages-config/test-input.yaml
> Wrap date inputs in fieldset with legend

- src/main/java/org/codeforamerica/shiba/pages/data/PagesData.java
- src/main/resources/application-demo.yaml
- src/main/resources/application-production.yaml
- src/main/resources/application.yaml
- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/CCAPMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/journeys/AccessibilityJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
- src/test/resources/application-test.yaml
Adding tribal nation member screen and feature-flag, `apply-for-tribal-nation`
[#179256832]
Co-authored-by: Chibuisi E <cenyia@codeforamerica.org>
> Tribal nation member

- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/journeys/AccessibilityJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
> Implement Nations Boundary Screen

- build.gradle
- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/documents/AzureDocumentRepositoryService.java
- src/main/java/org/codeforamerica/shiba/documents/CombinedDocumentRepositoryService.java
- src/main/java/org/codeforamerica/shiba/documents/DocumentRepositoryService.java
- src/main/java/org/codeforamerica/shiba/documents/S3DocumentRepositoryService.java
- src/main/java/org/codeforamerica/shiba/output/pdf/PdfGenerator.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/data/UploadedDocument.java
- src/test/java/org/codeforamerica/shiba/DocumentRepositoryServiceTestConfig.java
- src/test/java/org/codeforamerica/shiba/ResubmissionServiceTest.java
- src/test/java/org/codeforamerica/shiba/framework/FeatureFlagTest.java
- src/test/java/org/codeforamerica/shiba/journeys/AccessibilityJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
- src/test/java/org/codeforamerica/shiba/pages/data/ApplicationDataSerializationTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractPageControllerTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/NonSessionScopedApplicationData.java
This is the ultimate way around our dependabot-cannot-access-secrets problem, also it's just better practice
https://www.pivotaltracker.com/story/show/179333981
> Make it so tests don't need credentials anymore

- src/main/java/org/codeforamerica/shiba/documents/AzureDocumentRepository.java
- src/main/java/org/codeforamerica/shiba/documents/CombinedDocumentRepository.java
- src/main/java/org/codeforamerica/shiba/documents/DocumentRepository.java
- src/main/java/org/codeforamerica/shiba/documents/S3DocumentRepository.java
- src/main/java/org/codeforamerica/shiba/output/pdf/PdfGenerator.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/data/UploadedDocument.java
- src/test/java/org/codeforamerica/shiba/DocumentRepositoryTestConfig.java
- src/test/java/org/codeforamerica/shiba/ResubmissionServiceTest.java
- src/test/java/org/codeforamerica/shiba/journeys/AccessibilityJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/DocumentUploadJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
- src/test/java/org/codeforamerica/shiba/pages/data/ApplicationDataSerializationTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractBasePageTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractPageControllerTest.java
DocumentRepositoryService is redundant, as Repositories are a type of Service
> Rename DocumentRepositoryService -> DocumentRepository

- src/main/java/org/codeforamerica/shiba/inputconditions/Condition.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/data/ApplicationData.java
- src/main/java/org/codeforamerica/shiba/pages/data/DatasourcePages.java
- src/main/java/org/codeforamerica/shiba/pages/data/PagesData.java
- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/main/resources/pdf-mappings.yaml
- src/test/java/org/codeforamerica/shiba/CCAPMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/pages/UserJourneyMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
> If clients report no income, show a new additional info screen

- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParser.java
- src/main/java/org/codeforamerica/shiba/output/caf/HomeAddressStreetMapper.java
- src/main/java/org/codeforamerica/shiba/output/caf/MailingAddressStreetMapper.java
- src/main/resources/application-demo.yaml
- src/main/resources/application-production.yaml
- src/main/resources/application.yaml
- src/main/resources/messages.properties
- src/main/resources/messages_es.properties
- src/main/resources/pages-config.yaml
- src/main/resources/templates/reviewInfo.html
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/MinimumSnapFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/applicationinputsmappers/HomeAddressStreetMapperTest.java
- src/test/java/org/codeforamerica/shiba/output/applicationinputsmappers/MailingAddressStreetMapperTest.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/output/xml/XmlGeneratorIntegrationTest.java
- src/test/java/org/codeforamerica/shiba/pages/UserJourneyMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
- src/test/resources/application-test.yaml
Deprecate flag and assume "true"
> Cleanup apply without address

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/TribalNation.java
- src/main/java/org/codeforamerica/shiba/output/MnitDocumentConsumer.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/RoutingDestinationService.java
- src/main/java/org/codeforamerica/shiba/pages/events/ApplicationSubmittedListener.java
- src/test/java/org/codeforamerica/shiba/ResubmissionServiceTest.java
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- src/test/java/org/codeforamerica/shiba/pages/events/ApplicationSubmittedListenerTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractBasePageTest.java
- Also fix bug where ccap was wrongly being sent to Mille Lacs
> Resubmit tribal nations apps properly

- src/main/java/org/codeforamerica/shiba/SessionLogFilter.java
- src/main/java/org/codeforamerica/shiba/configurations/SecurityConfiguration.java
> Create audit logs for all admin endpoint accesses

- src/main/java/org/codeforamerica/shiba/pages/RoutingDestinationService.java
- src/main/resources/application-demo.yaml
- src/main/resources/application-production.yaml
- src/main/resources/application.yaml
- src/main/resources/pages-config.yaml
- src/main/resources/templates/success.html
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
- src/test/resources/application-test.yaml
> Remove apply for mille lacs flag

- src/main/java/org/codeforamerica/shiba/TribalNationRoutingDestination.java
- src/main/java/org/codeforamerica/shiba/inputconditions/ValueMatcher.java
- src/main/java/org/codeforamerica/shiba/mnit/TribalNationConfiguration.java
- src/main/java/org/codeforamerica/shiba/pages/RoutingDecisionService.java
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/pages/TribalNationsMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
https://www.pivotaltracker.com/story/show/179456928
> White earth routing

- build.gradle
* Use double quotes instead of single quotes
* Disambiguate function invocations and property assignments 
* Remove unused AWS dependencies
> Clean up build.gradle

- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParser.java
- src/main/java/org/codeforamerica/shiba/mnit/TribalNationConfiguration.java
- src/main/java/org/codeforamerica/shiba/pages/RoutingDecisionService.java
- src/test/java/org/codeforamerica/shiba/pages/TribalNationsMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
https://www.pivotaltracker.com/story/show/179456931
> Routing logic for Red Lake

- src/main/resources/messages.properties
- src/main/resources/static/shiba.js
- src/test/java/org/codeforamerica/shiba/journeys/AccessibilityJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/MinimumSnapFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractBasePageTest.java
> Pre-check text & email opt in on contact page

- src/main/resources/pages-config.yaml
- Add comments to explain landmark pages
Co-authored-by: Jayne Evjen <jayne.evjen@state.mn.us>
> prepareToApply is not a startTimerPage or postSubmitPage

- src/main/java/org/codeforamerica/shiba/County.java
- src/main/java/org/codeforamerica/shiba/application/parsers/CountyParser.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/java/org/codeforamerica/shiba/pages/data/ApplicationData.java
- src/test/java/org/codeforamerica/shiba/application/ApplicationRepositoryTest.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
[#179988477]
Co-authored-by: Jayne Evjen <jayne.evjen@state.mn.us>
> Record routing destinations in application data

- src/main/resources/pages-config.yaml
> Fix incorrect county dropdown values causing enum parsing failures

- src/main/resources/templates/fragments/inputs/date-input.html
> Show numpad for date inputs on mobile

- src/main/java/org/codeforamerica/shiba/County.java
> Add empty check for county

- src/main/resources/static/shiba.js
> Add null check to preCheckContactInfo method in SHIBA JS

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/output/FileDownloadController.java
- src/main/java/org/codeforamerica/shiba/output/MnitDocumentConsumer.java
- src/main/java/org/codeforamerica/shiba/output/caf/FilenameGenerator.java
- src/main/java/org/codeforamerica/shiba/output/pdf/PdfGenerator.java
- src/main/java/org/codeforamerica/shiba/output/xml/XmlGenerator.java
- src/test/java/org/codeforamerica/shiba/ResubmissionServiceTest.java
- src/test/java/org/codeforamerica/shiba/output/FileDownloadControllerTest.java
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- src/test/java/org/codeforamerica/shiba/output/applicationinputsmappers/FilenameGeneratorTest.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfGeneratorTest.java
> Bug Fix - Filenames are incorrect for Tribal nations

- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/main/resources/templates/noPhoneNumberConfirmation.html
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
> Implement no phone number confirmation screen

- src/main/java/org/codeforamerica/shiba/output/caf/GrossMonthlyIncomePreparer.java
- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/AdultRequestingChildcarePreparer.java
- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/DocumentFieldPreparers.java
- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/FullNamePreparer.java
- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/MonthlyFrequencyPreparer.java
- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/OneToOneDocumentFieldPreparer.java
- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/SubworkflowIterationScopeTracker.java
- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/SubworkflowPreparer.java
- src/test/java/org/codeforamerica/shiba/output/caf/GrossMonthlyIncomePreparerTest.java
- src/test/java/org/codeforamerica/shiba/output/documentfieldpreparers/AdultRequestingChildcarePreparerTest.java
- src/test/java/org/codeforamerica/shiba/output/documentfieldpreparers/DocumentFieldPreparersTest.java
- src/test/java/org/codeforamerica/shiba/output/documentfieldpreparers/FullNamePreparerTest.java
- src/test/java/org/codeforamerica/shiba/output/documentfieldpreparers/OneToOneDocumentFieldPreparerTest.java
- src/test/java/org/codeforamerica/shiba/output/documentfieldpreparers/SubworkflowPreparerTest.java
https://www.pivotaltracker.com/story/show/180239973
> Remove flatMap where possible

- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/test/java/org/codeforamerica/shiba/application/ApplicationRepositoryTest.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
> Only updating status if it is not already "delivered"

- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/main/resources/templates/addOtherPrograms.html
- src/main/resources/templates/canWeAsk.html
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
> Implement certain pops Add other programs screen

- src/main/java/org/codeforamerica/shiba/application/parsers/CountyParser.java
- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/MailingAddressStreetPreparer.java
- src/main/java/org/codeforamerica/shiba/pages/enrichment/GeneralDeliveryAddressEnrichment.java
- src/main/resources/application.yaml
- src/test/java/org/codeforamerica/shiba/application/parsers/CountyParserTest.java
- src/test/java/org/codeforamerica/shiba/framework/SubmissionAndTerminalPageTest.java
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/MinimumSnapFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/pages/TribalNationsMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/pages/enrichment/GeneralDeliveryAddressEnrichmentTest.java
> Deprecating  use-county-selection flag - defaults to "ON"

- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/output/caf/CoverPagePreparer.java
- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/ApplicantProgramsPreparer.java
- src/main/java/org/codeforamerica/shiba/pages/data/ApplicationData.java
- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/main/resources/templates/certainPopsConfirm.html
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfMockMvcTest.java
> Implemented certain Pops confirmation screen

- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/mnit/AlfrescoWebServiceClient.java
- src/main/java/org/codeforamerica/shiba/mnit/FilenetWebServiceClient.java
- src/main/java/org/codeforamerica/shiba/output/Document.java
- src/main/java/org/codeforamerica/shiba/output/MnitDocumentConsumer.java
- src/main/java/org/codeforamerica/shiba/pages/emails/EmailContentCreator.java
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- Only functional change is that it does no longer updates the caf_status when sending the xml
> Adding XML document type for logging purposes

- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/resources/messages.properties
- src/main/resources/templates/uploadDocuments.html
- src/test/java/org/codeforamerica/shiba/journeys/DocumentUploadJourneyTest.java
Now if there is an uncaught exception during doc upload, a default error message will be displayed with the following content:
> There was an issue processing this file on our end. Sorry about that! Please try another file or upload a screenshot instead.
https://www.pivotaltracker.com/story/show/179224795
> Fix bug where doc upload error messages contained html

- src/main/resources/pages-config.yaml
> Update Dakota County Later Docs to go to Email Page

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/Application.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationStatus.java
- src/main/java/org/codeforamerica/shiba/application/parsers/DocumentListParser.java
- src/main/java/org/codeforamerica/shiba/output/MnitDocumentConsumer.java
- src/main/java/org/codeforamerica/shiba/pages/RoutingDecisionService.java
- src/main/resources/application.yaml
- src/test/java/org/codeforamerica/shiba/ResubmissionServiceTest.java
- src/test/java/org/codeforamerica/shiba/application/ApplicationRepositoryTest.java
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- Removed "delivered" check since in_progress is only set on "inProgressStatusPage"
Wait until Filenet changes are in prod to deploy this change
> Reading from new application status table

- src/main/java/org/codeforamerica/shiba/application/parsers/ApplicationDataParser.java
- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/SavingsPreparer.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfMockMvcTest.java
> If an applicant says 0 for liquid assets mark No on savings

- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/HaveSavingsPreparer.java
- src/main/resources/pdf-mappings.yaml
> Update have savings key in pdf-mappings.yaml

- src/main/resources/application.yaml
> Turn on filenet

- src/main/resources/static/shiba.css
- src/main/resources/templates/documentRecommendation.html
- src/main/resources/templates/error.html
- src/main/resources/templates/faq.html
- src/main/resources/templates/fragments/pageTemplateFragment.html
- src/main/resources/templates/fragments/toolbar.html
- src/main/resources/templates/householdDeleteWarningPage.html
- src/main/resources/templates/jobBuilder.html
- src/main/resources/templates/jobDeleteWarningPage.html
- src/main/resources/templates/jobRedirectPage.html
- src/main/resources/templates/landing.html
- src/main/resources/templates/noProgramsSelected.html
- src/main/resources/templates/privacyPolicy.html
- src/main/resources/templates/snapExpeditedDetermination.html
- src/main/resources/templates/uploadDocuments.html
- src/main/resources/templates/uploadDocumentsDeleteWarningPage.html
> Add skip to content link and use landmarks for main and navigation

- src/main/resources/templates/householdList.html
> Add screen reader properties to household delete

- src/main/resources/pages-config.yaml
- src/main/resources/templates/fragments/form-question-prompt.html
- src/main/resources/templates/fragments/inputs/yes-no-input.html
- src/main/resources/templates/fragments/pageTemplateFragment.html
- src/main/resources/templates/fragments/promptMessageFragments/addHouseholdMembersPrompt.html
[#180249966]
- describedby uses header, header help message, prompt message key and prompt message fragments for description
> Update Yes/No pages to use aria-describedby

- src/main/resources/templates/fragments/inputs/checkbox-input.html
[#180249898]
Co-authored-by: Andrew Edstrom <aedstrom@codeforamerica.org>
> Update checkbox-input.html to use legend inside of fieldset

- src/main/resources/pages-config.yaml
> Allow empty phone number in later-docs

- src/main/resources/messages.properties
- src/test/java/org/codeforamerica/shiba/pages/emails/EmailContentCreatorTest.java
> Update confirmation email for Expedited CCAP and Expedited SNAP

- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/pages/UserJourneyMockMvcTest.java
[#180216747]
Co-authored-by: Touhid Khan <touhid.khan@state.mn.us>
> Make doc upload available to all clients

- src/main/java/org/codeforamerica/shiba/output/MnitDocumentConsumer.java
- src/main/java/org/codeforamerica/shiba/pages/emails/EmailClient.java
- src/main/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClient.java
- src/main/resources/application-production.yaml
- src/main/resources/application-staging.yaml
- src/main/resources/application.yaml
- src/test/java/org/codeforamerica/shiba/output/MnitDocumentConsumerTest.java
- src/test/java/org/codeforamerica/shiba/pages/emails/MailGunEmailClientTest.java
Remove functionality and feature flag
[#180906590]
> Remove hennepin doc emails

- src/main/java/db/migration/V34__BackfillApplicationStatus.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/application/DocumentStatusRepository.java
- src/main/resources/db/migration/V33__create-application-status-table.sql
- src/main/resources/db/migration/V35__remove-xxx-status-columns-from-applications.sql
- src/main/resources/db/migration/V36__change-application-status-to-document-status.sql
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractRepositoryTest.java
- src/test/resources/test-schema-init.sql
[#180197141]
#599 
Waiting on code changes related to the pull request above to be deployed to prod.
> Reapplying DB changes from previous pull request

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/application/DocumentStatusRepository.java
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/main/resources/application.yaml
- src/test/java/org/codeforamerica/shiba/AppsStuckInProgressResubmissionTest.java
- src/test/java/org/codeforamerica/shiba/ResubmissionServiceTest.java
- src/test/java/org/codeforamerica/shiba/application/DocumentStatusRepositoryTest.java
- src/test/resources/application-test.yaml
[#181078443]
Co-authored-by: Britney E <bepps@codeforamerica.org>
Co-authored-by: Taylor Johnson <taylor.johnson@state.mn.us>
> Resubmit apps stuck in progress

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/application/DocumentStatusRepository.java
- Only refire completed in_progress apps completed after December 6th
[#181078443]
Co-authored-by: Taylor Johnson <taylor.johnson@state.mn.us>
> Delete old statuses when refiring completed in_progress apps

- src/main/java/org/codeforamerica/shiba/output/caf/LiquidAssetsPreparer.java
- src/main/resources/pdf-mappings.yaml
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/MinimumSnapFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/output/caf/LiquidAssetsPreparerTest.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfMockMvcTest.java
[#181049190]
Co-authored-by: Taylor J Johnson <taylor.johnson@state.mn.us>
> Writing 0 savings to the CAF

- src/main/resources/templates/fragments/head.html
> Add Optimizely script with integrity hash

- src/main/java/org/codeforamerica/shiba/output/documentfieldpreparers/NoSocialSecurityNumberPreparer.java
- src/test/java/org/codeforamerica/shiba/output/documentfieldpreparers/NoSocialSecurityNumberPreparerTest.java
> Guard against SSN field being set to null

- src/main/java/org/codeforamerica/shiba/exception/controller/ControllerAdvisor.java
- src/test/java/org/codeforamerica/shiba/output/ResendFailedEmailControllerTest.java
[#181050258]
Co-authored-by: Touhid Khan <touhid.khan@state.mn.us>
> SocketException Error

- src/main/resources/static/shiba.css
- src/main/resources/templates/fragments/pageTemplateFragment.html
https://www.pivotaltracker.com/story/show/180250831
> Contact info spacing update

- src/main/resources/templates/fragments/inputs/registerToVoteInput.html
- src/test/java/org/codeforamerica/shiba/journeys/AccessibilityJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
> Fix tab stops on register to vote page

- build.gradle
- src/main/java/org/codeforamerica/shiba/pages/PageController.java
Thumbnails take >1min to appear when refreshing the uploadDocuments page with 20 uploads - Code Refactor
[#179210663]
Co-authored-by: Taylor J Johnson <taylor.johnson@state.mn.us>
> Thumbnails take >1min to appear when refreshing the uploadDocuments page

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/resources/application.yaml
- src/test/java/org/codeforamerica/shiba/AppsWithBlankStatusResubmissionTest.java
- src/test/java/org/codeforamerica/shiba/ResubmissionServiceTest.java
- src/test/resources/application-test.yaml
Co-authored-by: Alex G <agonzalez@codeforamerica.org>
Co-authored-by: Chibuisi E<cenyia@codeforamerica.org>
> Resubmission service for no statuses

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/ApplicationRepository.java
- src/main/java/org/codeforamerica/shiba/application/Status.java
- src/test/java/org/codeforamerica/shiba/AppsWithBlankStatusResubmissionTest.java
- src/test/java/org/codeforamerica/shiba/application/ApplicationRepositoryTest.java
- src/test/java/org/codeforamerica/shiba/application/DocumentStatusRepositoryTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/TestApplicationDataBuilder.java
> Fix blank statuses not being created for apps with docs

- src/main/java/org/codeforamerica/shiba/output/caf/UnearnedIncomeCafCalculator.java
- src/test/java/org/codeforamerica/shiba/output/caf/UnearnedIncomeCafCalculatorTest.java
> UnearnedIncomeCalculator ignore non-number, non-decimal characters

- src/main/resources/messages.properties
- src/main/resources/messages_es.properties
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/LaterDocsJourneyTest.java
> Stop requiring DOB

- src/main/java/org/codeforamerica/shiba/ResubmissionService.java
- src/main/java/org/codeforamerica/shiba/application/Status.java
- src/test/java/org/codeforamerica/shiba/ResubmissionServiceTest.java
[#180723079]
Co-authored-by: Taylor Johnson <taylor.johnson@state.mn.us>
> Add "delivered-by-email" application/document status

- src/main/resources/application-demo.yaml
- src/main/resources/application-staging.yaml
- src/main/resources/application.yaml
- src/main/resources/templates/fragments/demoBanner.html
- src/main/resources/templates/fragments/head.html
- src/test/java/org/codeforamerica/shiba/pages/DemoBannerTest.java
[#181669210]
@kmccrary
Co-authored-by: Britney Epps<bepps@codeforamerica.org>
> Search Crawler meta tag to block crawling one demo sites.

- src/main/resources/messages.properties
- src/main/resources/templates/uploadDocuments.html
- src/test/java/org/codeforamerica/shiba/journeys/DocumentUploadJourneyTest.java
> HEIC specific error message

- src/main/java/org/codeforamerica/shiba/pages/PageController.java
- src/test/java/org/codeforamerica/shiba/pages/PageControllerTest.java
- src/test/resources/pages-config/test-pages-controller.yaml
out to client to upload again..
[#181796284]
> There was an issue processing and delivering uploaded documents. Reach

- src/main/java/org/codeforamerica/shiba/inputconditions/ValueMatcher.java
- src/main/resources/pages-config.yaml
- src/test/java/org/codeforamerica/shiba/CCAPMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/framework/ConditionalInputsTest.java
- src/test/java/org/codeforamerica/shiba/inputconditions/ValueMatcherTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
- src/test/resources/pages-config/test-conditional-inputs.yaml
- Remove unused condition anchors
[#181716010]
Chibuisi Enyia <cenyia@codeforamerica.org>
> Hide drug felony question unless only CCAP is selected

- src/main/resources/templates/faq.html
- src/main/resources/templates/fragments/localeSelect.html
- src/main/resources/templates/landing.html
> Add lang attributes on 'Aplica Ahora' and Espanol language picker

- src/main/java/org/codeforamerica/shiba/SessionLogFilter.java
> logging code should not start a web session

- src/main/java/org/codeforamerica/shiba/pages/config/Validation.java
> Catch IndexOutOfBoundsException parsing DOB

- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/main/resources/templates/fragments/contextFragments.html
- src/main/resources/templates/timeoutNotice.html
- src/test/java/org/codeforamerica/shiba/journeys/AccessibilityJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/JourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/LocalePreferenceSelectionTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractBasePageTest.java
Add session timeout notice page
[#181434543]
@kmccrary
Co-Authored by: John Bisek <john.bisek@state.mn.us>
> Session notice

- src/main/resources/messages.properties
- src/main/resources/templates/privacyPolicy.html
[#181851913]
Co-Authored by: Britney Epps <bepps@codeforamerica.org>
> Privacy policy still points to ApplyMN - update the language

- src/test/java/org/codeforamerica/shiba/testutilities/AbstractBasePageTest.java
Co-authored-by: Ken McCrary <kmccrary@codeforamerica.org>
> [#182248862]

- src/main/java/org/codeforamerica/shiba/output/caf/FilenameGenerator.java
- src/test/java/org/codeforamerica/shiba/output/documentfieldpreparers/FilenameGeneratorTest.java
- Remove unused condition anchors
[#182266443]
Chibuisi Enyia <cenyia@codeforamerica.org>
Co-authored-by: Touhid Khan <Touhid.Khan@state.mn.us>
> Hennepin docs with MNB in the filename instead of DOC

- build.gradle
- src/main/java/org/codeforamerica/shiba/output/caf/FilenameGenerator.java
- src/main/resources/pdf-mappings.yaml
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/output/xml/XmlGeneratorIntegrationTest.java
Write other health coverage to the Certain Pops form
[#181933869]
Chibuisi Enyia <cenyia@codeforamerica.org>
Co-authored-by: Touhid Khan <Touhid.Khan@state.mn.us>
Co-authored-by: Taylor Johnson <taylor.johnson@state.mn.us>
> Write other health coverage to the Certain Pops form (rebase)

- src/main/resources/messages.properties
- src/main/resources/templates/fragments/inputs/householdOptionsCheckboxesWithFollowup.html
[#181743087]
Had to override the background color for the text box because the class for the $ sign has an off-white color.
> Changed income source to lowercase. Input boxes background all white.

- src/main/resources/messages.properties
- src/main/resources/pages-config.yaml
- src/main/resources/templates/fragments/inputs/householdOptionsCheckboxes.html
- src/test/java/org/codeforamerica/shiba/CCAPMockMvcTest.java
- src/test/java/org/codeforamerica/shiba/journeys/AccessibilityJourneyTest.java
- src/test/java/org/codeforamerica/shiba/journeys/FullFlowJourneyTest.java
- src/test/java/org/codeforamerica/shiba/pages/AssetsTypeTest.java
- src/test/java/org/codeforamerica/shiba/testutilities/AbstractShibaMockMvcTest.java
> Add 'Who' pages for assets

- src/test/java/org/codeforamerica/shiba/output/documentfieldpreparers/HouseholdSpousePreparerTest.java
- src/test/java/org/codeforamerica/shiba/output/pdf/PdfMockMvcTest.java
> Certain pop spouse q4 test
